name:                Pipo
version:             0.1.0.0
github:              "Shou/Pipo"
license:             GPL3
author:              "Shou"
maintainer:          "x+gh@shou.io"
copyright:           "2020 Shou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Pipo#readme>

dependencies:
- base >= 4.7 && < 5
- discord-haskell == 1.2.0
- aeson == 1.4.6.0
- optparse-applicative == 0.14.3.0
- text == 1.2.3.1
- bytestring == 0.10.8.2
- random == 1.1
- attoparsec == 0.13.2.3

default-extensions:
  - GADTs
  - BlockArguments
  - OverloadedStrings
  - TypeApplications
  - LambdaCase
  - RecordWildCards
  - DeriveGeneric
  - DeriveAnyClass

library:
  source-dirs: src

executables:
  Pipo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Pipo

tests:
  Pipo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Pipo
